// This code automatically generated by TableCodeGen
using UnityEngine;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.UI;
using TMPro;

public class LoadText : MonoBehaviour
{
    public TextAsset file;
    public int Index;
    public TextMeshProUGUI narration;

    private void Start()
    {
        narration = GetComponent<TextMeshProUGUI>();
        Load(file);
        Debug.Log(GetAt(Index).Phrase);
        narration.text = GetAt(Index).Phrase;
    }

    public class Row
    {
        public string Phrase;
    }

    List<Row> rowList = new List<Row>();
    bool isLoaded = false;

    public bool IsLoaded()
    {
        return isLoaded;
    }

    public List<Row> GetRowList()
    {
        return rowList;
    }

    public void Load(TextAsset csv)
    {
        rowList.Clear();
        string[][] grid = CsvParser2.Parse(csv.text);
        for (int i = 1; i < grid.Length; i++)
        {
            Row row = new Row();
            row.Phrase = grid[i][0];

            rowList.Add(row);
        }
        isLoaded = true;
    }

    public int NumRows()
    {
        return rowList.Count;
    }

    public Row GetAt(int i)
    {
        if (rowList.Count <= i)
            return null;
        return rowList[i];
    }

    public Row Find_Phrase(string find)
    {
        return rowList.Find(x => x.Phrase == find);
    }
    public List<Row> FindAll_Phrase(string find)
    {
        return rowList.FindAll(x => x.Phrase == find);
    }

}